CREATE TABLE userinfo
(
    "USER_ID"           BIGSERIAL NOT NULL,
    "NAME"              VARCHAR(100),
    "SUB"               VARCHAR(150),
    "CREATED_ON"        BIGINT,
    CONSTRAINT "User_PK" PRIMARY KEY ( "USER_ID" )
);

CREATE TABLE workspace
(
    "WORKSPACE_ID"      BIGSERIAL NOT NULL,
    "USER_ID"            BIGINT NOT NULL,
    "TYPE"              VARCHAR(100),
    "WORKSPACE_NAME"    VARCHAR(100),
    "CREATED_ON"        BIGINT,
    CONSTRAINT "Workspace_PK" PRIMARY KEY ( "WORKSPACE_ID" ),
    CONSTRAINT "Workspace_FK" FOREIGN KEY ( "USER_ID" ) REFERENCES "userinfo" ( "USER_ID" ) ON DELETE CASCADE
);

CREATE TABLE wishlist
(
    "WISHLIST_ID"   BIGSERIAL NOT NULL,
    "USER_ID"       BIGINT NOT NULL,
    "WORKSPACE_ID"  BIGINT,
    "DATE"          BIGINT NOT NULL,
    "SYMBOL"        VARCHAR(100) NOT NULL,
    "EXCHANGE"      VARCHAR(100),
    "PRICE"         DECIMAL NOT NULL,
    CONSTRAINT "Wishlist_PK" PRIMARY KEY ( "WISHLIST_ID" ),
    CONSTRAINT "Wishlist_FK" FOREIGN KEY ( "USER_ID" ) REFERENCES "userinfo" ( "USER_ID" ) ON DELETE CASCADE,
    CONSTRAINT "Wishlist_FK1" FOREIGN KEY ( "WORKSPACE_ID" ) REFERENCES "workspace" ( "WORKSPACE_ID" )
);

CREATE TABLE holdings
(
    "HOLDINGS_ID"   BIGSERIAL NOT NULL,
    "USER_ID"       BIGINT NOT NULL,
    "WORKSPACE_ID"  BIGINT,
    "DATE"          BIGINT NOT NULL,
    "SYMBOL"        VARCHAR(100) NOT NULL,
    "EXCHANGE"      VARCHAR(100),
    "QUANTITY"      INT NOT NULL,
    "PRICE"         DECIMAL NOT NULL,
    "UPDATED_DATE"  BIGINT,
    CONSTRAINT "Holdings_PK" PRIMARY KEY ( "HOLDINGS_ID" ),
    CONSTRAINT "Holdings_FK" FOREIGN KEY ( "USER_ID" ) REFERENCES "userinfo" ( "USER_ID" ) ON DELETE CASCADE,
    CONSTRAINT "Holdings_FK1" FOREIGN KEY ( "WORKSPACE_ID" ) REFERENCES "workspace" ( "WORKSPACE_ID" )
);

CREATE TABLE sold
(
    "SOLD_ID"       BIGSERIAL NOT NULL,
    "USER_ID"       BIGINT NOT NULL,
    "DATE"          BIGINT NOT NULL,
    "SYMBOL"        VARCHAR(100) NOT NULL,
    "EXCHANGE"      VARCHAR(100),
    "QUANTITY"      INT NOT NULL,
    "BUY_PRICE"     DECIMAL NOT NULL,
    "SELL_PRICE"     DECIMAL NOT NULL,
    CONSTRAINT "Solds_PK" PRIMARY KEY ( "SOLD_ID" ),
    CONSTRAINT "Solds_FK" FOREIGN KEY ( "USER_ID" ) REFERENCES "userinfo" ( "USER_ID" ) ON DELETE CASCADE
);

CREATE TABLE transactions
(
    "TRANSACTION_ID"    BIGSERIAL NOT NULL,
    "USER_ID"           BIGINT NOT NULL,
    "TYPE"              VARCHAR(100) NOT NULL,
    "DATE"              BIGINT NOT NULL,
    "SYMBOL"            VARCHAR(100) NOT NULL,
    "EXCHANGE"          VARCHAR(100),
    "QUANTITY"          INT NOT NULL,
    "PRICE"             DECIMAL NOT NULL,
    "AMOUNT"            DECIMAL NOT NULL,
    CONSTRAINT "Transactions_PK" PRIMARY KEY ( "TRANSACTION_ID" ),
    CONSTRAINT "Transactions_FK" FOREIGN KEY ( "USER_ID" ) REFERENCES "userinfo" ( "USER_ID" ) ON DELETE CASCADE
)